version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    command: [ "redis-server", "--slaveof", "no one", "--requirepass", "isylzjko" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: isylzjko
      POSTGRES_DB: 8BuildIn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: prakit@gmail.com
      PGADMIN_DEFAULT_PASSWORD: isylzjko
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data:
