module.exports = {
  AuthController: require('./auth.controller'),
  CustomerController: require('./customer.controller'),
  EmployeeController: require('./employee.controller'),
  LicenseController: require('./license.controller'),
  MaterialCategoryController: require('./material-category.controller'),
  MaterialController: require('./material.controller'),
  MenuController: require('./menu.controller'),
  PermissionController: require('./permission.controller'),
  ProductCategoryController: require('./product-category.controller'),
  ProductController: require('./product.controller'),
  StockInController: require('./stock-in.controller'),
  StockOutController: require('./stock-out.controller'),
  SupplierController: require('./supplier.controller'),
  UnitController: require('./unit.controller'),
  CartController: require('./cart.controller'),
  PurchaseRequestController: require('./purchase-request.controller'),
  PurchaseOrderController: require('./purchase-order.controller'),
}
