module.exports = {
  CustomerModel: require('./customer.model'),
  EmployeeModel: require('./employee.model'),
  LicenseModel: require('./license.model'),
  MaterialCategoryModel: require('./material-category.model'),
  MaterialModel: require('./material.model'),
  MenuModel: require('./menu.model'),
  PermissionModel: require('./permission.model'),
  ProductCategoryModel: require('./product-category.model'),
  ProductModel: require('./product.model'),
  StockInModel: require('./stock-in.model'),
  StockOutModel: require('./stock-out.model'),
  SupplierModel: require('./supplier.model'),
  UnitModel: require('./unit.model'),
  CartModel: require('./cart.model'),
  PurchaseRequestModel: require('./purchase-request.model'),
}
